// Code generated by scripts/upgradeshim/prepare-upgrade-shim-embed.sh; DO NOT EDIT.

//go:build darwin && arm64

package embed

import _ "embed"

//go:embed assets/upgrade-shim-darwin-arm64.zst
var embeddedUpgradeShim_darwin_arm64 []byte

func init() {
	register(Asset{
		SourceDigest: "5d0ea08f4c2ca1e03d84d6bf335a5b26df0031c112f9c98ee0ab502d283117d0",
		SHA256:       "162376e573664ff5dac2cd5da83faae54d3bb63a890ca08b051b08afb9484268",
		Zstd:         embeddedUpgradeShim_darwin_arm64,
	})
}
